### ISSUE TITLE
Tailwind plugin

### ISSUE THREAD

**Issue by kripod** [mirisuzanne/cascading-color-system#14]
I just came across this project [on miriamsuzanne.com](https://www.miriamsuzanne.com/contact/), noticing how balanced the colors are on that site, especially for the dark backgrounds. With Tailwind CSS, semantically [named colors](https://tailwindcss.com/docs/customizing-colors#naming-your-colors) may be used.

I thought offering a Tailwind plugin for generating palettes from a single color could be useful and increase the adoption of this groundbreaking aspect to color systems on the web.

**Comment by mirisuzanne** [comment]
Hi @kripod - thanks!

I've never used Tailwind, so I have no idea what that would involve. I probably don't want to maintain a plugin as part of this core repo, but you are absolutely welcome to make it if you want. I'll happily link to it as a resource for anyone interested!

**Comment by kripod** [comment]
Thank you for your quick response!

I’m not sure when I’ll have some spare time to work on a plugin, as it would also require a headless JS implementation for all the SCSS functions involved. It seems to be a significant amount of work to deliver that while maintaining compatibility with the SCSS version.
